# run the buoygrab file and upload the data to the docker server for gitaction 

name: 'buoy-grab'
on: push

jobs:
  buoy-grab:
    name: run buoygrab.py
    runs-on: ubuntu-latest
    container:
      image: python:3.11
      options: --user root
      volumes:
        - buoy-grab:/buoy-grab
    steps:
      - name: Running python install
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests
          pip3 install BeautifulSoup4
      - name: Run buoygrab
        run: |
          python3 buoygrab.py
